# API Testing (Health Check)
GET https://backend-134-820401822458.us-central1.run.app/ HTTP/1.1

###
# GET : All Notes
GET https://backend-134-820401822458.us-central1.run.app/api/v1/notes HTTP/1.1
Content-Type: application/json

###
# POST : Create Note
POST https://backend-134-820401822458.us-central1.run.app/api/v1/notes HTTP/1.1
Content-Type: application/json

{
  "judul": "test 123",
  "isi": "ini pesan note gwe"
}

###
# GET : Note by ID
# (PENTING: Ganti angka 1 di bawah dengan ID asli yang ada di database)
GET https://backend-134-820401822458.us-central1.run.app/api/v1/notes/1 HTTP/1.1
Content-Type: application/json

###
# PUT : Update Note
# (PENTING: Ganti angka 1 di bawah dengan ID asli yang ada di database)
PUT https://backend-134-820401822458.us-central1.run.app/api/v1/notes/1 HTTP/1.1
Content-Type: application/json

{
  "judul": "ini update",
  "isi": "notenya update via Cloud Run"
}

###
# DELETE : Delete Note
# (PENTING: Ganti angka 1 di bawah dengan ID asli yang ada di database)
DELETE https://backend-134-820401822458.us-central1.run.app/api/v1/notes/1 HTTP/1.1
Content-Type: application/json